### ISSUE TITLE
Improve scanner.startScanning() API

### ISSUE THREAD

**Issue by itkach** [manateeworks/phonegap-mwbarcodescanner#1]
Currently [scanner.startScanning() in MWBScanner.js](https://github.com/manateeworks/phonegap-mwbarcodescanner/blob/master/www/MWBScanner.js#L176) takes no arguments, scan result is simply shown in an alert. This is not useful in actual applications. 
A better startScanning() would look something like this: 

``` javascript
scanner.startScanning = function(callback, options) {
    //Configure BarcodeScanner
    var actualOptions = options || {};
    Object.keys(options).forEach(function(key){
        //Call BarcodeScanner.MWBset* corresponding to given key
    });
    //Scan and pass the result to the callback function given
    BarcodeScanner.MWBstartScanning(callback);
} 
```

**Comment by pieweb** [comment]
How do I make this change in Phonegap BUILD? I don't think I can edit MWBScanner.js, can I?

**Comment by manateeworks** [comment]
Hello pieweb,

You can change MWBScanner.js of course, but when you update the plugin, your changes will be overwritten. Since version 1.4 we have allowed users to put their own callback and decoder initialization function in scanner.startScanning. Please refer to notes inside MWBScanner.js file.

Regards
